# Generated by Django 2.2.4 on 2019-09-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('crimetype', models.CharField(max_length=100)),
                ('describecrime', models.TextField(max_length=100)),
                ('crimelocation', models.CharField(max_length=50)),
                ('youraddress', models.TextField(max_length=100)),
            ],
        ),
    ]
