# Generated by Django 2.2.4 on 2019-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
